export enum CustomError {
    UNEXPECTED = "UNEXPECTED",
    ALREADY_EXISTS = "ALREADY_EXISTS",
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
    NOT_FOUND = "NOT_FOUND",
    NOT_ALLOWED = "NOT_ALLOWED"
}